language: python
python:
  - "2.7"
  - "3.5"
#  - "3.7" waiting for support in travis https://github.com/travis-ci/travis-ci/issues/9552
install:
  - pip install ansible-lint
script:
  - if ansible-lint -r rules tests/*.yml; then (exit 2); else (exit 0); fi
